# Options for analysis running.
run:
  timeout: 10m
  concurrency: 4

linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - gofmt
    - goheader
    - goimports
    - gosec
    - misspell
    - nakedret
    - nestif
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - gocyclo
    - revive

linters-settings:
  staticcheck:
    checks: ["all"]
